[theme]
base = "dark"
primaryColor = "#E47A0A"
backgroundColor = "#080C18"
secondaryBackgroundColor = "#12182A"
textColor = "#F8FAFC"
font = "sans-serif"
baseRadius = "large"
buttonRadius = "full"
showWidgetBorder = true

[theme.sidebar]
backgroundColor = "#1d6679"
secondaryBackgroundColor = "#171F34"