[theme]
base = "dark"
primaryColor = "#E47A0A"
backgroundColor = "#3C20A3"
secondaryBackgroundColor = "#80003A"
textColor = "#000000"
font = "sans-serif"
baseRadius = "large"
buttonRadius = "full"
showWidgetBorder = true

[theme.sidebar]
backgroundColor = "#FFFF"
secondaryBackgroundColor = "#16cec5"