[theme]
base = "dark"
primaryColor = "#7AA6D7"
backgroundColor = "#080C18"
secondaryBackgroundColor = "#12182A"
textColor = "#F8FAFC"
font = "sans-serif"
baseRadius = "large"
buttonRadius = "full"
showWidgetBorder = true

[theme.sidebar]
backgroundColor = "#B2B3B5"
secondaryBackgroundColor = "#171F34"